name: Deploy Next.js site to GitHub Pages

on:
  push:
    branches:
      - main  # Replace this with your main development branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3  # Use v3 of setup-node
        with:
          node-version: '18.17.0'  # Specify Node.js version 18.17.0 or higher

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out  # Deploys contents of 'out' to 'gh-pages' branch
